-- 코드를 입력하세요
SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES A
LEFT JOIN (
    SELECT ID, NAME, HOST_ID, COUNT(HOST_ID) CNT   
    FROM PLACES
    GROUP BY HOST_ID
) B USING(HOST_ID)
WHERE B.CNT >= 2
ORDER BY ID;