-- 코드를 입력하세요
SELECT distinct CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
USING(CAR_ID)
WHERE A.CAR_TYPE = '세단'
AND B.START_DATE >= '2022-10-01'
ORDER BY CAR_ID DESC;